# Generated by Django 4.2 on 2026-05-12 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approval_status', models.CharField(choices=[('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=20)),
                ('approved_by', models.CharField(default='Admin', max_length=100)),
                ('approved_date', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approvals', to='student.student')),
            ],
            options={
                'db_table': 'student_approval',
                'ordering': ['-approved_date'],
            },
        ),
    ]
